# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DownLink
                                 A QGIS plugin
 Easily download Sentinel-2 raster data from the public S3 bucket
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-02-03
        copyright            : (C) 2024 by Dean Sherwin
        email                : downlink@deansherwin.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DownLink class from file DownLink.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .down_link import DownLink
    return DownLink(iface)
